name: generate profile assets

on:
  # run automatically every 2 hours
  schedule:
    - cron: "0 */2 * * *" 

  # allows manual run
  workflow_dispatch:

  # run on push to master
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # generate snake animation
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # generate stats card
      - name: generate stats card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: stats
          options: username=${{ github.repository_owner }}&theme=bear&margin-w=50&cache_seconds=7200
          path: dist/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # generate trophy card
      - name: generate trophy card
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: username=${{ github.repository_owner }}&theme=onedark&no-frame=true
          path: dist/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # generate top languages card
      - name: generate top languages card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&theme=bear&layout=compact&langs_count=6
          path: dist/top-languages.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # push generated assets to output branch
      - name: push assets to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
