name: generate trophy cards

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # checkout repository to get access to the repo
      - name: checkout repository
        uses: actions/checkout@v3
      
      # generate stats card
      - name: generate stats card
        uses: soulteary/github-readme-stats-action@v1.0.0
        with:
          card: stats
          options: username=${{ github.repository_owner }}&theme=onedark&margin-w=50&cache_seconds=7200
          path: dist/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # generate trophy card
      - name: generate trophy card
        uses: soulteary/github-profile-trophy-action@v1.0.0
        with:
          options: username=${{ github.repository_owner }}&theme=onedark&no-frame=true
          path: dist/trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push trophy cards to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}